local T = _G.T
local autolist = require('autolist')

T.describe('FR-5 toggling a checkbox', function()
  T.it('checks an unchecked box and back', function()
    local buf = T.buf({ '- [ ] 未' })
    T.cursor(1, 0)
    T.truthy(autolist.toggle_checkbox())
    T.eq({ '- [x] 未' }, T.lines(buf))
    T.truthy(autolist.toggle_checkbox())
    T.eq({ '- [ ] 未' }, T.lines(buf))
  end)

  T.it('unchecks an uppercase X as well', function()
    local buf = T.buf({ '- [X] 済み' })
    T.cursor(1, 0)
    autolist.toggle_checkbox()
    T.eq({ '- [ ] 済み' }, T.lines(buf))
  end)

  T.it('works on an ordered item, in a blockquote, and while nested', function()
    local buf = T.buf({ '> 1. [ ] a', '    - [ ] b' })
    autolist.toggle_checkbox(1)
    autolist.toggle_checkbox(2)
    T.eq({ '> 1. [x] a', '    - [x] b' }, T.lines(buf))
  end)

  T.it('does nothing on an item without a checkbox', function()
    local buf = T.buf({ '- plain' })
    T.cursor(1, 0)
    T.falsy(autolist.toggle_checkbox())
    T.eq({ '- plain' }, T.lines(buf))
  end)

  T.it('does nothing on a line that is not an item', function()
    local buf = T.buf({ 'a [ ] b' })
    T.cursor(1, 0)
    T.falsy(autolist.toggle_checkbox())
    T.eq({ 'a [ ] b' }, T.lines(buf))
  end)
end)
