local T = _G.T
local autolist = require('autolist')
local config = require('autolist.config')

local function with_setup(opts, fn)
  autolist.setup(opts)
  local ok, err = pcall(fn)
  autolist.setup({})
  if not ok then
    error(err, 0)
  end
end

T.describe('configuration', function()
  T.it('needs no setup call to work on markdown (NFR-4)', function()
    T.truthy(config.get(T.buf({ '- a' })))
  end)

  T.it('leaves filetypes that are not enabled alone', function()
    T.eq(nil, config.get(T.buf({ '- a' }, 'python')))
  end)

  T.it('enables another filetype without losing markdown', function()
    with_setup({ filetypes = { text = {} } }, function()
      local buf = T.buf({ '- a' }, 'text')
      T.cursor_eol(1)
      T.truthy(autolist.newline())
      T.eq({ '- a', '- ' }, T.lines(buf))
      T.truthy(config.get(T.buf({ '- a' }, 'markdown')))
    end)
  end)

  T.it('disables a filetype set to false', function()
    with_setup({ filetypes = { markdown = false } }, function()
      T.eq(nil, config.get(T.buf({ '- a' })))
    end)
  end)

  T.it('uses a custom cycle order', function()
    with_setup({ filetypes = { markdown = { cycle = { '-', '1.' } } } }, function()
      local buf = T.buf({ '- a' })
      T.cursor(1, 0)
      autolist.cycle_markers()
      T.eq({ '1. a' }, T.lines(buf))
      autolist.cycle_markers()
      T.eq({ '- a' }, T.lines(buf))
    end)
  end)

  T.it('writes and re-reads a custom checkbox character', function()
    with_setup({ filetypes = { markdown = { checkbox = { checked = 'v', unchecked = '.' } } } }, function()
      local buf = T.buf({ '- [.] a' })
      T.truthy(autolist.toggle_checkbox(1))
      T.eq({ '- [v] a' }, T.lines(buf))
      T.truthy(autolist.toggle_checkbox(1))
      T.eq({ '- [.] a' }, T.lines(buf))
    end)
  end)

  T.it('still reads the standard characters when they are customised', function()
    with_setup({ filetypes = { markdown = { checkbox = { checked = 'v', unchecked = '.' } } } }, function()
      local buf = T.buf({ '- [x] a' })
      autolist.toggle_checkbox(1)
      T.eq({ '- [.] a' }, T.lines(buf))
    end)
  end)

  T.it('carries the configured unchecked character onto a new item', function()
    with_setup({ filetypes = { markdown = { checkbox = { checked = 'v', unchecked = '.' } } } }, function()
      local buf = T.buf({ '- [v] a' })
      T.cursor_eol(1)
      autolist.newline()
      T.eq({ '- [v] a', '- [.] ' }, T.lines(buf))
    end)
  end)
end)
