local T = _G.T
local autolist = require('autolist')

T.describe('FR-4 indenting an item', function()
  T.it('joins the siblings that already exist at the level below', function()
    local buf = T.buf({ '1. あ', '    1. か', '2. い', '3. う' })
    T.cursor(3, 0)
    T.truthy(autolist.indent())
    T.eq({ '1. あ', '    1. か', '    2. い', '2. う' }, T.lines(buf))
  end)

  T.it('starts a new level from the beginning', function()
    local buf = T.buf({ '1. あ', '2. い', '3. う' })
    T.cursor(2, 0)
    autolist.indent()
    T.eq({ '1. あ', '    1. い', '2. う' }, T.lines(buf))
  end)

  T.it('takes nested items and continuation lines along', function()
    local buf = T.buf({ '- あ', '- い', '  つづき', '    - こ', '- う' })
    T.cursor(2, 0)
    autolist.indent()
    T.eq({ '- あ', '    - い', '      つづき', '        - こ', '- う' }, T.lines(buf))
  end)

  T.it('refuses to indent the first item of a level', function()
    local buf = T.buf({ '1. あ', '2. い' })
    T.cursor(1, 0)
    T.falsy(autolist.indent())
    T.eq({ '1. あ', '2. い' }, T.lines(buf))
  end)

  T.it('dedents back to the level of the parent', function()
    local buf = T.buf({ '1. あ', '    1. か', '    2. い', '2. う' })
    T.cursor(3, 0)
    T.truthy(autolist.dedent())
    T.eq({ '1. あ', '    1. か', '2. い', '3. う' }, T.lines(buf))
  end)

  T.it('refuses to dedent an item that has no parent', function()
    local buf = T.buf({ '1. あ', '2. い' })
    T.cursor(2, 0)
    T.falsy(autolist.dedent())
    T.eq({ '1. あ', '2. い' }, T.lines(buf))
  end)

  T.it('keeps a list that repeats one number as it is', function()
    local buf = T.buf({ '1. あ', '1. い', '1. う' })
    T.cursor(2, 0)
    autolist.indent()
    T.eq({ '1. あ', '    1. い', '1. う' }, T.lines(buf))
  end)

  T.it('follows the buffer indent settings', function()
    local buf = T.buf({ '- あ', '- い' })
    vim.bo[buf].shiftwidth = 2
    T.cursor(2, 0)
    autolist.indent()
    T.eq({ '- あ', '  - い' }, T.lines(buf))
  end)
end)
