local T = _G.T
local autolist = require('autolist')

T.describe('FR-1 continuing a list on newline', function()
  T.it('repeats an unordered marker', function()
    local buf = T.buf({ '- りんご' })
    T.cursor_eol(1)
    T.truthy(autolist.newline())
    T.eq({ '- りんご', '- ' }, T.lines(buf))
    T.eq({ 2, 2 }, vim.api.nvim_win_get_cursor(0))
  end)

  T.it('advances an ordered marker', function()
    local buf = T.buf({ '1. りんご' })
    T.cursor_eol(1)
    autolist.newline()
    T.eq({ '1. りんご', '2. ' }, T.lines(buf))
  end)

  T.it('keeps the indent and the delimiter of the source line', function()
    local buf = T.buf({ '    a) りんご' })
    T.cursor_eol(1)
    autolist.newline()
    T.eq({ '    a) りんご', '    b) ' }, T.lines(buf))
  end)

  T.it('carries a checkbox over, always unchecked', function()
    local buf = T.buf({ '- [x] 済み' })
    T.cursor_eol(1)
    autolist.newline()
    T.eq({ '- [x] 済み', '- [ ] ' }, T.lines(buf))

    buf = T.buf({ '- [ ] 未' })
    T.cursor_eol(1)
    autolist.newline()
    T.eq({ '- [ ] 未', '- [ ] ' }, T.lines(buf))
  end)

  T.it('moves the text after the cursor into the new item', function()
    local buf = T.buf({ '- りんごばなな' })
    T.cursor(1, #'- りんご')
    autolist.newline()
    T.eq({ '- りんご', '- ばなな' }, T.lines(buf))
    T.eq({ 2, 2 }, vim.api.nvim_win_get_cursor(0))
  end)

  T.it('keeps the same number when the list repeats one number', function()
    local buf = T.buf({ '1. あ', '1. い' })
    T.cursor_eol(2)
    autolist.newline()
    T.eq({ '1. あ', '1. い', '1. ' }, T.lines(buf))
  end)

  T.it('counts up when the numbers differ', function()
    local buf = T.buf({ '1. あ', '2. い' })
    T.cursor_eol(2)
    autolist.newline()
    T.eq({ '1. あ', '2. い', '3. ' }, T.lines(buf))
  end)

  T.it('keeps the blockquote markers', function()
    local buf = T.buf({ '> - りんご' })
    T.cursor_eol(1)
    autolist.newline()
    T.eq({ '> - りんご', '> - ' }, T.lines(buf))
  end)

  T.it('reads an ambiguous letter the way its siblings are written', function()
    local buf = T.buf({ 'i. あ', 'ii. い' })
    T.cursor_eol(2)
    autolist.newline()
    T.eq({ 'i. あ', 'ii. い', 'iii. ' }, T.lines(buf))
  end)

  T.it('does not continue from a continuation line', function()
    local buf = T.buf({ '- りんご。説明が長いので', '  2 行目に続いている' })
    T.cursor_eol(2)
    T.falsy(autolist.newline())
    T.eq({ '- りんご。説明が長いので', '  2 行目に続いている' }, T.lines(buf))
  end)

  T.it('leaves the key alone when the cursor is inside the marker', function()
    T.buf({ '- りんご' })
    T.cursor(1, 0)
    T.falsy(autolist.newline())
  end)
end)

T.describe('FR-2 leaving the list from an empty item', function()
  T.it('clears an empty item', function()
    local buf = T.buf({ '- りんご', '- ' })
    T.cursor_eol(2)
    T.truthy(autolist.newline())
    T.eq({ '- りんご', '' }, T.lines(buf))
    T.eq({ 2, 0 }, vim.api.nvim_win_get_cursor(0))
  end)

  T.it('clears an empty item that only holds a checkbox', function()
    local buf = T.buf({ '- [ ] りんご', '- [ ] ' })
    T.cursor_eol(2)
    autolist.newline()
    T.eq({ '- [ ] りんご', '' }, T.lines(buf))
  end)

  T.it('clears a nested empty item down to the margin', function()
    local buf = T.buf({ '- りんご', '    - ' })
    T.cursor_eol(2)
    autolist.newline()
    T.eq({ '- りんご', '' }, T.lines(buf))
  end)

  T.it('stays inside the blockquote', function()
    local buf = T.buf({ '> - りんご', '> - ' })
    T.cursor_eol(2)
    autolist.newline()
    T.eq({ '> - りんご', '> ' }, T.lines(buf))
  end)
end)

T.describe('FR-8 other lines keep their own behaviour', function()
  T.it('does nothing on a plain line', function()
    T.buf({ 'just a paragraph' })
    T.cursor_eol(1)
    T.falsy(autolist.newline())
  end)

  T.it('does nothing in a buffer of another filetype', function()
    T.buf({ '- りんご' }, 'python')
    T.cursor_eol(1)
    T.falsy(autolist.newline())
  end)

  T.it('reports through cr() whether it wants the key', function()
    T.buf({ '- りんご', 'paragraph' })
    T.cursor_eol(1)
    T.truthy(autolist.cr())
    T.cursor_eol(2)
    T.eq(nil, autolist.cr())
  end)
end)
