local T = _G.T
local autolist = require('autolist')

T.describe('FR-10 continuing a list when a line is added', function()
  T.it('repeats an unordered marker below', function()
    local buf = T.buf({ '- りんご' })
    T.cursor_eol(1)
    T.truthy(autolist.open_below())
    T.eq({ '- りんご', '- ' }, T.lines(buf))
    T.eq({ 2, 2 }, vim.api.nvim_win_get_cursor(0))
  end)

  T.it('advances an ordered marker below', function()
    local buf = T.buf({ '1. りんご' })
    T.cursor_eol(1)
    autolist.open_below()
    T.eq({ '1. りんご', '2. ' }, T.lines(buf))
  end)

  T.it('takes the number of the item it is placed above', function()
    local buf = T.buf({ '1. あ', '2. い' })
    T.cursor_eol(2)
    T.truthy(autolist.open_above())
    T.eq({ '1. あ', '2. ', '2. い' }, T.lines(buf))
    T.eq({ 2, 3 }, vim.api.nvim_win_get_cursor(0))
  end)

  T.it('adds above the first line of the buffer', function()
    local buf = T.buf({ '- りんご' })
    T.cursor_eol(1)
    autolist.open_above()
    T.eq({ '- ', '- りんご' }, T.lines(buf))
    T.eq({ 1, 2 }, vim.api.nvim_win_get_cursor(0))
  end)

  T.it('keeps the indent and the delimiter of the source line', function()
    local buf = T.buf({ '    a) りんご' })
    T.cursor_eol(1)
    autolist.open_below()
    T.eq({ '    a) りんご', '    b) ' }, T.lines(buf))
  end)

  T.it('carries a checkbox over, always unchecked', function()
    local buf = T.buf({ '- [x] 済み' })
    T.cursor_eol(1)
    autolist.open_below()
    T.eq({ '- [x] 済み', '- [ ] ' }, T.lines(buf))
  end)

  T.it('keeps the same number when the list repeats one number', function()
    local buf = T.buf({ '1. あ', '1. い' })
    T.cursor_eol(2)
    autolist.open_below()
    T.eq({ '1. あ', '1. い', '1. ' }, T.lines(buf))
  end)

  T.it('keeps the blockquote markers', function()
    local buf = T.buf({ '> - りんご' })
    T.cursor_eol(1)
    autolist.open_below()
    T.eq({ '> - りんご', '> - ' }, T.lines(buf))
  end)

  T.it('reads an ambiguous letter the way its siblings are written', function()
    local buf = T.buf({ 'i. あ', 'ii. い' })
    T.cursor_eol(2)
    autolist.open_below()
    T.eq({ 'i. あ', 'ii. い', 'iii. ' }, T.lines(buf))
  end)

  T.it('leaves the current line whole wherever the cursor sits in it', function()
    local buf = T.buf({ '- りんごばなな' })
    T.cursor(1, #'- りんご')
    autolist.open_below()
    T.eq({ '- りんごばなな', '- ' }, T.lines(buf))

    buf = T.buf({ '- りんご' })
    T.cursor(1, 0)
    T.truthy(autolist.open_below())
    T.eq({ '- りんご', '- ' }, T.lines(buf))
  end)

  T.it('goes on from an empty item instead of leaving the list', function()
    local buf = T.buf({ '- りんご', '- ' })
    T.cursor_eol(2)
    T.truthy(autolist.open_below())
    T.eq({ '- りんご', '- ', '- ' }, T.lines(buf))
  end)

  T.it('does not continue from a continuation line', function()
    local buf = T.buf({ '- りんご。説明が長いので', '  2 行目に続いている' })
    T.cursor_eol(2)
    T.falsy(autolist.open_below())
    T.falsy(autolist.open_above())
    T.eq({ '- りんご。説明が長いので', '  2 行目に続いている' }, T.lines(buf))
  end)

  T.it('does nothing inside a code block', function()
    local buf = T.buf({ '```', '- りんご', '```' })
    T.cursor_eol(2)
    T.falsy(autolist.open_below())
    T.eq({ '```', '- りんご', '```' }, T.lines(buf))
  end)
end)

T.describe('FR-8 other lines keep their own behaviour', function()
  T.it('does nothing on a plain line when a line is added', function()
    T.buf({ 'just a paragraph' })
    T.cursor_eol(1)
    T.falsy(autolist.open_below())
    T.falsy(autolist.open_above())
  end)

  T.it('does nothing in a buffer of another filetype', function()
    T.buf({ '- りんご' }, 'python')
    T.cursor_eol(1)
    T.falsy(autolist.open_below())
  end)

  T.it('reports through o() and shift_o() whether it wants the key', function()
    T.buf({ '- りんご', 'paragraph' })
    T.cursor_eol(1)
    T.truthy(autolist.o())
    T.truthy(autolist.shift_o())
    T.cursor_eol(2)
    T.eq(nil, autolist.o())
    T.eq(nil, autolist.shift_o())
  end)
end)
