local T = _G.T
local autolist = require('autolist')

T.describe('FR-3 renumbering an ordered list', function()
  T.it('makes the numbers consecutive', function()
    local buf = T.buf({ '1. あ', '5. い', '2. う' })
    T.cursor(1, 0)
    T.truthy(autolist.renumber())
    T.eq({ '1. あ', '2. い', '3. う' }, T.lines(buf))
  end)

  T.it('counts each level on its own', function()
    local buf = T.buf({ '1. 親', '    5. 子', '    9. 子', '3. 親' })
    T.cursor(1, 0)
    autolist.renumber()
    T.eq({ '1. 親', '    5. 子', '    6. 子', '2. 親' }, T.lines(buf))
  end)

  T.it('respects the number the level starts from', function()
    local buf = T.buf({ '3. あ', '7. い', '9. う' })
    T.cursor(2, 0)
    autolist.renumber()
    T.eq({ '3. あ', '4. い', '5. う' }, T.lines(buf))
  end)

  T.it('leaves a list that repeats one number alone', function()
    local buf = T.buf({ '1. あ', '1. い', '1. う' })
    T.cursor(1, 0)
    T.falsy(autolist.renumber())
    T.eq({ '1. あ', '1. い', '1. う' }, T.lines(buf))
  end)

  T.it('leaves unordered lists alone', function()
    local buf = T.buf({ '- あ', '- い' })
    T.cursor(1, 0)
    T.falsy(autolist.renumber())
    T.eq({ '- あ', '- い' }, T.lines(buf))
  end)

  T.it('handles letters and Roman numerals', function()
    local buf = T.buf({ 'a) あ', 'c) い', 'b) う' })
    T.cursor(1, 0)
    autolist.renumber()
    T.eq({ 'a) あ', 'b) い', 'c) う' }, T.lines(buf))

    buf = T.buf({ 'I. あ', 'V. い', 'II. う' })
    T.cursor(1, 0)
    autolist.renumber()
    T.eq({ 'I. あ', 'II. い', 'III. う' }, T.lines(buf))
  end)

  T.it('keeps each item written the way it was', function()
    local buf = T.buf({ '1. あ', '5) い', '9. う' })
    T.cursor(1, 0)
    autolist.renumber()
    T.eq({ '1. あ', '2) い', '3. う' }, T.lines(buf))
  end)

  T.it('does not reach past a blank line', function()
    local buf = T.buf({ '1. あ', '2. い', '', '1. う', '5. え' })
    T.cursor(4, 0)
    autolist.renumber()
    T.eq({ '1. あ', '2. い', '', '1. う', '2. え' }, T.lines(buf))
  end)

  T.it('reaches across continuation lines', function()
    local buf = T.buf({ '1. あ', '   内容の 2 行目', '5. い' })
    T.cursor(1, 0)
    autolist.renumber()
    T.eq({ '1. あ', '   内容の 2 行目', '2. い' }, T.lines(buf))
  end)

  T.it('stops at a line that is neither an item nor a continuation', function()
    local buf = T.buf({ '1. あ', 'paragraph', '5. い', '9. う' })
    T.cursor(3, 0)
    autolist.renumber()
    T.eq({ '1. あ', 'paragraph', '5. い', '6. う' }, T.lines(buf))
  end)

  T.it('renumbers inside a blockquote and keeps the quote markers', function()
    local buf = T.buf({ '> 1. あ', '> 5. い' })
    T.cursor(1, 0)
    autolist.renumber()
    T.eq({ '> 1. あ', '> 2. い' }, T.lines(buf))
  end)

  T.it('has no line limit of its own', function()
    local lines = { '9. item 1' }
    for i = 2, 300 do
      lines[i] = '1. item ' .. i
    end
    local buf = T.buf(lines)
    T.cursor(1, 0)
    autolist.renumber()
    local got = T.lines(buf)
    T.eq('9. item 1', got[1])
    T.eq('10. item 2', got[2])
    T.eq('308. item 300', got[300])
  end)
end)
